/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Units;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Random;

/**
 *
 * @author Lenovo
 */
public class GameGUI extends javax.swing.JFrame implements KeyListener {

    static Scanner scanner = new Scanner(System.in);
    static String buffer = "";
    static int consoleLOCK = 1;
    
    private Thread thread;
    private boolean running = false;
    
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }
    
    public synchronized void start(){
        thread = new Thread((Runnable) this);
        thread.start();
        running = true;
    }
    
    public synchronized void stop(){
        try{
            thread.join();
            running = false;
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public GameGUI() {        
        initComponents();
        console.addKeyListener(this);
        console.setEditable(false);
        
        consoleLOCK = 0;
            if(consoleLOCK == 0){
                console.append("+=============+  New Game  +=============+\n");
                console.append("You awake to a new day...\n" 
                                + "Stepping outside the inn,\n" 
                                + "the warmth of the twins Prima and Secunda illuminate the village of West Haven.\n" 
                                + "You take a deep breath, filling your lungs with the country air.\n"
                                + "It's a new day and a new opportunity to earn your fair share of coin...\n"
                                + "Press <Enter> to continue");
            }
            
            if(consoleLOCK == 1){
                console.append("A mercenary by trade, you lead a small band of loyal men.\n"
                                + "Before you embark to fulfill the newest contract ");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Player1 = new javax.swing.JPanel();
        btnPlayer1 = new javax.swing.JButton();
        player4 = new javax.swing.JPanel();
        btnPlayer4 = new javax.swing.JButton();
        enemy1 = new javax.swing.JPanel();
        btnPlayer3 = new javax.swing.JButton();
        enemy4 = new javax.swing.JPanel();
        btnPlayer7 = new javax.swing.JButton();
        Player2 = new javax.swing.JPanel();
        btnPlayer2 = new javax.swing.JButton();
        Player3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        player5 = new javax.swing.JPanel();
        btnPlayer5 = new javax.swing.JButton();
        enemy2 = new javax.swing.JPanel();
        btnPlayer8 = new javax.swing.JButton();
        enemy5 = new javax.swing.JPanel();
        btnPlayer9 = new javax.swing.JButton();
        player6 = new javax.swing.JPanel();
        btnPlayer6 = new javax.swing.JButton();
        enemy3 = new javax.swing.JPanel();
        btnPlayer10 = new javax.swing.JButton();
        enemy6 = new javax.swing.JPanel();
        btnPlayer11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Player1.setBackground(new java.awt.Color(0, 153, 255));

        btnPlayer1.setBackground(new java.awt.Color(255, 51, 102));
        btnPlayer1.setText("Player1");
        btnPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Player1Layout = new javax.swing.GroupLayout(Player1);
        Player1.setLayout(Player1Layout);
        Player1Layout.setHorizontalGroup(
            Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Player1Layout.setVerticalGroup(
            Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 176));

        player4.setBackground(new java.awt.Color(255, 51, 102));

        btnPlayer4.setBackground(new java.awt.Color(255, 51, 102));
        btnPlayer4.setText("Player4");

        javax.swing.GroupLayout player4Layout = new javax.swing.GroupLayout(player4);
        player4.setLayout(player4Layout);
        player4Layout.setHorizontalGroup(
            player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        player4Layout.setVerticalGroup(
            player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(player4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        enemy1.setBackground(new java.awt.Color(51, 0, 255));

        btnPlayer3.setBackground(new java.awt.Color(102, 204, 255));
        btnPlayer3.setText("Enemy1");
        btnPlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enemy1Layout = new javax.swing.GroupLayout(enemy1);
        enemy1.setLayout(enemy1Layout);
        enemy1Layout.setHorizontalGroup(
            enemy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        enemy1Layout.setVerticalGroup(
            enemy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(enemy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        enemy4.setBackground(new java.awt.Color(51, 153, 0));

        btnPlayer7.setBackground(new java.awt.Color(102, 204, 255));
        btnPlayer7.setText("Enemy4");
        btnPlayer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enemy4Layout = new javax.swing.GroupLayout(enemy4);
        enemy4.setLayout(enemy4Layout);
        enemy4Layout.setHorizontalGroup(
            enemy4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        enemy4Layout.setVerticalGroup(
            enemy4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(enemy4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));

        Player2.setBackground(new java.awt.Color(51, 0, 255));

        btnPlayer2.setBackground(new java.awt.Color(255, 51, 102));
        btnPlayer2.setText("Player2");
        btnPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Player2Layout = new javax.swing.GroupLayout(Player2);
        Player2.setLayout(Player2Layout);
        Player2Layout.setHorizontalGroup(
            Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Player2Layout.setVerticalGroup(
            Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, -1, -1));

        Player3.setBackground(new java.awt.Color(255, 102, 204));

        jButton9.setBackground(new java.awt.Color(255, 51, 102));
        jButton9.setText("Player3");

        javax.swing.GroupLayout Player3Layout = new javax.swing.GroupLayout(Player3);
        Player3.setLayout(Player3Layout);
        Player3Layout.setHorizontalGroup(
            Player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Player3Layout.setVerticalGroup(
            Player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Player3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Player3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 354, -1, -1));

        player5.setBackground(new java.awt.Color(102, 102, 255));

        btnPlayer5.setBackground(new java.awt.Color(255, 51, 102));
        btnPlayer5.setText("Player5");

        javax.swing.GroupLayout player5Layout = new javax.swing.GroupLayout(player5);
        player5.setLayout(player5Layout);
        player5Layout.setHorizontalGroup(
            player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        player5Layout.setVerticalGroup(
            player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(player5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 177, -1, -1));

        enemy2.setBackground(new java.awt.Color(102, 0, 102));

        btnPlayer8.setBackground(new java.awt.Color(102, 204, 255));
        btnPlayer8.setText("Enemy2");
        btnPlayer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enemy2Layout = new javax.swing.GroupLayout(enemy2);
        enemy2.setLayout(enemy2Layout);
        enemy2Layout.setHorizontalGroup(
            enemy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        enemy2Layout.setVerticalGroup(
            enemy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(enemy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 177, -1, -1));

        enemy5.setBackground(new java.awt.Color(0, 102, 102));

        btnPlayer9.setBackground(new java.awt.Color(102, 204, 255));
        btnPlayer9.setText("Enemy5");
        btnPlayer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enemy5Layout = new javax.swing.GroupLayout(enemy5);
        enemy5.setLayout(enemy5Layout);
        enemy5Layout.setHorizontalGroup(
            enemy5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        enemy5Layout.setVerticalGroup(
            enemy5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(enemy5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 177, -1, -1));

        player6.setBackground(new java.awt.Color(51, 0, 255));

        btnPlayer6.setBackground(new java.awt.Color(255, 51, 102));
        btnPlayer6.setText("Player6");

        javax.swing.GroupLayout player6Layout = new javax.swing.GroupLayout(player6);
        player6.setLayout(player6Layout);
        player6Layout.setHorizontalGroup(
            player6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        player6Layout.setVerticalGroup(
            player6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(player6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 354, -1, -1));

        enemy3.setBackground(new java.awt.Color(153, 51, 0));

        btnPlayer10.setBackground(new java.awt.Color(102, 204, 255));
        btnPlayer10.setText("Enemy3");
        btnPlayer10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enemy3Layout = new javax.swing.GroupLayout(enemy3);
        enemy3.setLayout(enemy3Layout);
        enemy3Layout.setHorizontalGroup(
            enemy3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        enemy3Layout.setVerticalGroup(
            enemy3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer10, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(enemy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 354, -1, -1));

        enemy6.setBackground(new java.awt.Color(0, 255, 102));

        btnPlayer11.setBackground(new java.awt.Color(102, 204, 255));
        btnPlayer11.setText("Enemy6");
        btnPlayer11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enemy6Layout = new javax.swing.GroupLayout(enemy6);
        enemy6.setLayout(enemy6Layout);
        enemy6Layout.setHorizontalGroup(
            enemy6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        enemy6Layout.setVerticalGroup(
            enemy6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemy6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPlayer11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(enemy6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 354, 250, -1));

        console.setColumns(20);
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1000, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer1ActionPerformed

    private void btnPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer2ActionPerformed

    private void btnPlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer3ActionPerformed

    private void btnPlayer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer7ActionPerformed

    private void btnPlayer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer8ActionPerformed

    private void btnPlayer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer9ActionPerformed

    private void btnPlayer10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer10ActionPerformed

    private void btnPlayer11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayer11ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Player1;
    private javax.swing.JPanel Player2;
    private javax.swing.JPanel Player3;
    private javax.swing.JButton btnPlayer1;
    private javax.swing.JButton btnPlayer10;
    private javax.swing.JButton btnPlayer11;
    private javax.swing.JButton btnPlayer2;
    private javax.swing.JButton btnPlayer3;
    private javax.swing.JButton btnPlayer4;
    private javax.swing.JButton btnPlayer5;
    private javax.swing.JButton btnPlayer6;
    private javax.swing.JButton btnPlayer7;
    private javax.swing.JButton btnPlayer8;
    private javax.swing.JButton btnPlayer9;
    private javax.swing.JTextArea console;
    private javax.swing.JPanel enemy1;
    private javax.swing.JPanel enemy2;
    private javax.swing.JPanel enemy3;
    private javax.swing.JPanel enemy4;
    private javax.swing.JPanel enemy5;
    private javax.swing.JPanel enemy6;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel player4;
    private javax.swing.JPanel player5;
    private javax.swing.JPanel player6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {}

    @Override
    public void keyPressed(KeyEvent e) {
        if(e.getKeyCode() == KeyEvent.VK_ENTER && consoleLOCK == 0) {
            console.setText("");
            consoleLOCK = 1;
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {}
}
