/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Units;

import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class viewCharacters extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public viewCharacters() {
        initComponents();
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnPsychic = new javax.swing.JButton();
        btnBerserker = new javax.swing.JButton();
        btnBarbarian = new javax.swing.JButton();
        btnWitchDoctor = new javax.swing.JButton();
        btnJuggernaut = new javax.swing.JButton();
        btnMarksman = new javax.swing.JButton();
        playerCharLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerCharStat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnWarlock = new javax.swing.JButton();
        btnMarauder = new javax.swing.JButton();
        btnRogue = new javax.swing.JButton();
        btnSummoner = new javax.swing.JButton();
        btnBrute = new javax.swing.JButton();
        btnAssassin = new javax.swing.JButton();
        enemyCharLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        enemyCharStat = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnExit1 = new javax.swing.JButton();
        btnNewGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("League of Warriors: Characters");
        setPreferredSize(new java.awt.Dimension(1100, 760));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setForeground(new java.awt.Color(51, 0, 153));
        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTabbedPane3.setPreferredSize(new java.awt.Dimension(1100, 650));

        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel2.setPreferredSize(new java.awt.Dimension(990, 570));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPsychic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPsychic.setForeground(new java.awt.Color(0, 0, 153));
        btnPsychic.setText("Psychic");
        btnPsychic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPsychicActionPerformed(evt);
            }
        });
        jPanel2.add(btnPsychic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 481, 310, 90));
        btnPsychic.getAccessibleContext().setAccessibleName("");

        btnBerserker.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBerserker.setForeground(new java.awt.Color(0, 0, 153));
        btnBerserker.setText("Berserker");
        btnBerserker.setToolTipText("Click to View Character's Statistics");
        btnBerserker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerserkerActionPerformed(evt);
            }
        });
        jPanel2.add(btnBerserker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 310, 90));
        btnBerserker.getAccessibleContext().setAccessibleName("");

        btnBarbarian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBarbarian.setForeground(new java.awt.Color(0, 0, 153));
        btnBarbarian.setText("Barbarian");
        btnBarbarian.setToolTipText("");
        btnBarbarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarbarianActionPerformed(evt);
            }
        });
        jPanel2.add(btnBarbarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 310, 90));
        btnBarbarian.getAccessibleContext().setAccessibleName("");

        btnWitchDoctor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWitchDoctor.setForeground(new java.awt.Color(0, 0, 153));
        btnWitchDoctor.setText("Witch Doctor");
        btnWitchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWitchDoctorActionPerformed(evt);
            }
        });
        jPanel2.add(btnWitchDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 208, 310, 90));
        btnWitchDoctor.getAccessibleContext().setAccessibleName("");

        btnJuggernaut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnJuggernaut.setForeground(new java.awt.Color(0, 0, 153));
        btnJuggernaut.setText("Juggernaut");
        btnJuggernaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuggernautActionPerformed(evt);
            }
        });
        jPanel2.add(btnJuggernaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 299, 310, 90));
        btnJuggernaut.getAccessibleContext().setAccessibleName("");

        btnMarksman.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMarksman.setForeground(new java.awt.Color(0, 0, 153));
        btnMarksman.setText("Marksman");
        btnMarksman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarksmanActionPerformed(evt);
            }
        });
        jPanel2.add(btnMarksman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 310, 90));
        btnMarksman.getAccessibleContext().setAccessibleName("");

        jPanel2.add(playerCharLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 0, 450, 570));

        jScrollPane1.setWheelScrollingEnabled(false);

        playerCharStat.setEditable(false);
        playerCharStat.setColumns(20);
        playerCharStat.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        playerCharStat.setRows(5);
        playerCharStat.setText("Statistics");
        playerCharStat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        playerCharStat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        playerCharStat.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(playerCharStat);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 310, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Click a character's button to view its statistics");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 25));

        jTabbedPane4.addTab("View Player's Characters", jPanel2);

        jTabbedPane3.addTab("Player", jTabbedPane4);

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1100, 607));

        jPanel4.setPreferredSize(new java.awt.Dimension(990, 570));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWarlock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWarlock.setForeground(new java.awt.Color(0, 0, 153));
        btnWarlock.setText("Warlock");
        btnWarlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarlockActionPerformed(evt);
            }
        });
        jPanel4.add(btnWarlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 481, 310, 90));

        btnMarauder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMarauder.setForeground(new java.awt.Color(0, 0, 153));
        btnMarauder.setText("Marauder");
        btnMarauder.setToolTipText("Click to View Character's Statistics");
        btnMarauder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarauderActionPerformed(evt);
            }
        });
        jPanel4.add(btnMarauder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 310, 90));

        btnRogue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRogue.setForeground(new java.awt.Color(0, 0, 153));
        btnRogue.setText("Rogue");
        btnRogue.setToolTipText("");
        btnRogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRogueActionPerformed(evt);
            }
        });
        jPanel4.add(btnRogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 310, 90));

        btnSummoner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSummoner.setForeground(new java.awt.Color(0, 0, 153));
        btnSummoner.setText("Summoner");
        btnSummoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummonerActionPerformed(evt);
            }
        });
        jPanel4.add(btnSummoner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 208, 310, 90));

        btnBrute.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBrute.setForeground(new java.awt.Color(0, 0, 153));
        btnBrute.setText("Brute");
        btnBrute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBruteActionPerformed(evt);
            }
        });
        jPanel4.add(btnBrute, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 299, 310, 90));

        btnAssassin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAssassin.setForeground(new java.awt.Color(0, 0, 153));
        btnAssassin.setText("Assassin");
        btnAssassin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssassinActionPerformed(evt);
            }
        });
        jPanel4.add(btnAssassin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 310, 90));
        jPanel4.add(enemyCharLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 0, 450, 570));

        jScrollPane2.setWheelScrollingEnabled(false);

        enemyCharStat.setEditable(false);
        enemyCharStat.setColumns(20);
        enemyCharStat.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        enemyCharStat.setRows(5);
        enemyCharStat.setText("Statistics");
        enemyCharStat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        enemyCharStat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        enemyCharStat.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(enemyCharStat);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 310, 300));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Click a character's button to view its statistics");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("View Enemy Characters", jPanel3);

        jTabbedPane3.addTab("Enemy", jTabbedPane2);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, -1, 650));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(255, 0, 0));
        btnExit1.setText("EXIT");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 548, 70));

        btnNewGame.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        btnNewGame.setForeground(new java.awt.Color(255, 0, 0));
        btnNewGame.setText("NEW GAME");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 548, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 655, 1100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerserkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerserkerActionPerformed
        // TODO add your handling code here:
  
        //Create a new instance of Berserker object
        Berserker viewCharStat =  new Berserker();
        //Add the picture of the character to playerLabel and display its statistic
        try
        {
            playerCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/berserker1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            playerCharStat.setText(viewCharStat.getCombineStat());
            playerCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            playerCharStat.setEditable(false);
        }
    
    }//GEN-LAST:event_btnBerserkerActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        //Launch GameGUI
        new GameGUI().setVisible(true);
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        //Exit the program
        System.exit(0);
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnBarbarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarbarianActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of Barbarian object
        Barbarian viewCharStat =  new Barbarian();
        //Add the picture of the character to playerLabel and display its statistic
        try
        {
            playerCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/barbarian1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            playerCharStat.setText(viewCharStat.getCombineStat());
            playerCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            playerCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnBarbarianActionPerformed

    private void btnWitchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWitchDoctorActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of WitchDoctor object
        WitchDoctor viewCharStat =  new WitchDoctor();
        //Add the picture of the character to playerLabel and display its statistic
        try
        {
            playerCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/witch_doc1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            playerCharStat.setText(viewCharStat.getCombineStat());
            playerCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            playerCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnWitchDoctorActionPerformed

    private void btnJuggernautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuggernautActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of Juggernaut object
        Juggernaut viewCharStat =  new Juggernaut();
        //Add the picture of the character to playerLabel and display its statistic
        try
        {
            playerCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/juggernaut1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            playerCharStat.setText(viewCharStat.getCombineStat());
            playerCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            playerCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnJuggernautActionPerformed

    private void btnMarksmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarksmanActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of Marksman object
        Marksman viewCharStat =  new Marksman();
        //Add the picture of the character to playerLabel and display its statistic
        try
        {
            playerCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/marksman1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            playerCharStat.setText(viewCharStat.getCombineStat());
            playerCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            playerCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnMarksmanActionPerformed

    private void btnPsychicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPsychicActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of Psychic object
        Psychic viewCharStat =  new Psychic();
        //Add the picture of the character to playerLabel and display its statistic
        try
        {
            playerCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/psychic1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            playerCharStat.setText(viewCharStat.getCombineStat());
            playerCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            playerCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnPsychicActionPerformed

    private void btnWarlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarlockActionPerformed
        // TODO add your handling code here:
            
        //Create a new instance of enemy_Warlock object
        enemy_Warlock viewCharStat =  new enemy_Warlock();
        //Add the picture of the character to enemyLabel and display its statistic
        try
        {
            enemyCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/psychic1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            enemyCharStat.setText(viewCharStat.getCombineStat());
            enemyCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            enemyCharStat.setEditable(false);
        }
        
    }//GEN-LAST:event_btnWarlockActionPerformed

    private void btnMarauderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarauderActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of enemy_Marauder object
        enemy_Marauder viewCharStat =  new enemy_Marauder();
        //Add the picture of the character to enemyLabel and display its statistic
        try
        {
            enemyCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/psychic1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            enemyCharStat.setText(viewCharStat.getCombineStat());
            enemyCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            enemyCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnMarauderActionPerformed

    private void btnRogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRogueActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of enemy_Rogue object
        enemy_Rogue viewCharStat =  new enemy_Rogue();
        //Add the picture of the character to enemyLabel and display its statistic
        try
        {
            enemyCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/psychic1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            enemyCharStat.setText(viewCharStat.getCombineStat());
            enemyCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            enemyCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnRogueActionPerformed

    private void btnSummonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummonerActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of enemy_Summoner object
        enemy_Summoner viewCharStat =  new enemy_Summoner();
        //Add the picture of the character to enemyLabel and display its statistic
        try
        {
            enemyCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/psychic1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            enemyCharStat.setText(viewCharStat.getCombineStat());
            enemyCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            enemyCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnSummonerActionPerformed

    private void btnBruteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBruteActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of enemy_Brute object
        enemy_Brute viewCharStat =  new enemy_Brute();
        //Add the picture of the character to enemyLabel and display its statistic
        try
        {
            enemyCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/psychic1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            enemyCharStat.setText(viewCharStat.getCombineStat());
            enemyCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            enemyCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnBruteActionPerformed

    private void btnAssassinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssassinActionPerformed
        // TODO add your handling code here:
        
        //Create a new instance of enemy_Assassin object
        enemy_Assassin viewCharStat =  new enemy_Assassin();
        //Add the picture of the character to enemyLabel and display its statistic
        try
        {
            enemyCharLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/psychic1.jpg")));
        }// NOI18N
        catch(NullPointerException ex)
        {
            String message = ex.getMessage();
            System.out.println(message);
            System.out.println("Image file is missing!");
        }
        finally
        {   
            enemyCharStat.setText(viewCharStat.getCombineStat());
            enemyCharStat.setFont(new Font("Monospaced", Font.BOLD, 18));
            enemyCharStat.setEditable(false);
        }
    }//GEN-LAST:event_btnAssassinActionPerformed
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssassin;
    private javax.swing.JButton btnBarbarian;
    private javax.swing.JButton btnBerserker;
    private javax.swing.JButton btnBrute;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnJuggernaut;
    private javax.swing.JButton btnMarauder;
    private javax.swing.JButton btnMarksman;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnPsychic;
    private javax.swing.JButton btnRogue;
    private javax.swing.JButton btnSummoner;
    private javax.swing.JButton btnWarlock;
    private javax.swing.JButton btnWitchDoctor;
    private javax.swing.JLabel enemyCharLabel;
    private javax.swing.JTextArea enemyCharStat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel playerCharLabel;
    private javax.swing.JTextArea playerCharStat;
    // End of variables declaration//GEN-END:variables
}
